//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanIpCalculator.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanIpCalculator.Assets.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string ApplicationCalculate {
            get {
                return ResourceManager.GetString("ApplicationCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ApplicationClear {
            get {
                return ResourceManager.GetString("ApplicationClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string CaptionIP {
            get {
                return ResourceManager.GetString("CaptionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Length:.
        /// </summary>
        public static string CaptionMaskLength {
            get {
                return ResourceManager.GetString("CaptionMaskLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host IP: {0}.
        /// </summary>
        public static string ResultHostIP {
            get {
                return ResourceManager.GetString("ResultHostIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP range: {0} - {1}.
        /// </summary>
        public static string ResultIPRange {
            get {
                return ResourceManager.GetString("ResultIPRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max hosts amount: {0}.
        /// </summary>
        public static string ResultMaxHostsAmount {
            get {
                return ResourceManager.GetString("ResultMaxHostsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network broadcast IP: {0}.
        /// </summary>
        public static string ResultNetworkBroadcastIP {
            get {
                return ResourceManager.GetString("ResultNetworkBroadcastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network IP: {0}.
        /// </summary>
        public static string ResultNetworkIP {
            get {
                return ResourceManager.GetString("ResultNetworkIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet mask: {0}.
        /// </summary>
        public static string ResultSubnetMask {
            get {
                return ResourceManager.GetString("ResultSubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect IP address!.
        /// </summary>
        public static string WarningIP {
            get {
                return ResourceManager.GetString("WarningIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect subnet mask!.
        /// </summary>
        public static string WarningSubnetMask {
            get {
                return ResourceManager.GetString("WarningSubnetMask", resourceCulture);
            }
        }
    }
}
